CREATE TABLE NEXT_WORKFLOW_PROGRESS (
    RUN_KEY        VARCHAR2(120),
    EVENT_TS       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    IS_FINAL       VARCHAR2(1),
    JOB_ROUTE      VARCHAR2(50),
    JOB_INDEX      NUMBER,
    TOTAL_JOBS     NUMBER,
    STATUS         VARCHAR2(100),
    OK_YN          VARCHAR2(1),
    MAP_ID         NUMBER,
    SPACE_NM       VARCHAR2(200),
    SQL_ID         VARCHAR2(200),
    MESSAGE_TEXT   CLOB,
    PAYLOAD_JSON   CLOB
);

CREATE INDEX IX_NEXT_WORKFLOW_PROGRESS_01
    ON NEXT_WORKFLOW_PROGRESS (RUN_KEY, EVENT_TS);
