"""Experimental 10C executor: one LLM response creates MIG, count Verify, and full-row Verify SQL."""

from __future__ import annotations

import json
import importlib.util
from pathlib import Path
from typing import Any


_executor2_path = Path(__file__).with_name("10C_migOneJobPocExecutor2.py")
_executor2_spec = importlib.util.spec_from_file_location("smartmigrate_executor2_base", _executor2_path)
if _executor2_spec is None or _executor2_spec.loader is None:
    raise ImportError(f"Could not load Executor2 base: {_executor2_path}")
_executor2_module = importlib.util.module_from_spec(_executor2_spec)
_executor2_spec.loader.exec_module(_executor2_module)

Executor2Base = _executor2_module.NewType10CMigOneJobPocExecutor2
FAIL_TEST2 = _executor2_module.FAIL_TEST2


class NewType10CMigOneJobPocExecutor3(Executor2Base):
    """LLM-generated full-row verifier experiment, isolated from deterministic Executor2."""

    display_name = "10C MIG One Job Executor 3 (LLM Full-Row Verify)"
    description = "Generates migration SQL, count Verify SQL, and full-row concat comparison SQL in one LLM response."
    name = "NewType10CMigOneJobPocExecutor3"

    def _node_generate_sql(self, context: dict[str, Any]) -> dict[str, Any]:
        try:
            verify_only = context.get("failure_status") == "FAIL-TEST"
            migration_sql, verification_sql, full_row_compare_sql, used_model = self._generate_migration_bundle(context, verify_only=verify_only)
            if verify_only:
                migration_sql = str(
                    context.get("saved_migration_sql")
                    or context.get("current_migration_sql")
                    or context.get("migration_sql")
                    or ""
                ).strip()
            migration_sql = self._clean_sql_statement(migration_sql)
            verification_sql = self._clean_sql_statement(verification_sql)
            full_row_compare_sql = self._clean_sql_statement(full_row_compare_sql)
            if not migration_sql:
                raise ValueError("LLM response did not include migration_sql")
            if not verification_sql:
                raise ValueError("LLM response did not include verification_sql")
            if not full_row_compare_sql:
                raise ValueError("LLM response did not include full_row_compare_sql")
            return {
                "stage": "GENERATE_SQL",
                "status": "PASS",
                "message": f"migration/count/full-row SQL generated by LLM model={used_model}",
                "outputs": {
                    "migration_sql": migration_sql,
                    "verification_sql": verification_sql,
                    "full_row_compare_sql": full_row_compare_sql,
                    "generated_sql_columns": ["VERIFY_SQL"] if verify_only else ["MIG_SQL", "VERIFY_SQL"],
                    "llm_model": used_model,
                    "generated_sql_saved": False,
                },
            }
        except Exception as exc:
            return {
                "stage": "GENERATE_SQL",
                "status": "FAIL-INSERT",
                "message": f"migration SQL bundle generation failed: {exc}",
                "outputs": {
                    "migration_sql": context.get("current_migration_sql") or context.get("migration_sql", ""),
                    "verification_sql": context.get("current_v_sql") or context.get("verification_sql", ""),
                },
            }

    def _node_verify_records(self, context: dict[str, Any]) -> dict[str, Any]:
        """Execute the LLM-produced full-row SQL and always retain it for the log."""
        comparison_sql = str(context.get("full_row_compare_sql") or "").strip()
        try:
            if not comparison_sql:
                comparison_sql, used_model = self._generate_full_row_compare_only(context)
            comparison_sql = self._clean_sql_statement(comparison_sql)
            if not comparison_sql.upper().startswith("WITH"):
                raise ValueError("full_row_compare_sql must start with WITH")
            result = self._execute_full_row_comparison(
                dict(context.get("db_config") or {}),
                comparison_sql,
                [],
            )
            detail_json = json.dumps(result, ensure_ascii=False, default=str)
            return {
                "stage": "VERIFY_RECORDS",
                "status": "PASS" if result["ok"] else FAIL_TEST2,
                "message": result["summary"],
                "outputs": {
                    "record_projection_sql": comparison_sql,
                    "full_row_compare_sql": comparison_sql,
                    "record_verify_result": result,
                    "record_verify_detail": detail_json,
                },
            }
        except Exception as exc:
            return {
                "stage": "VERIFY_RECORDS",
                "status": FAIL_TEST2,
                "message": f"LLM full-row verification failed: {exc}",
                "outputs": {"record_projection_sql": comparison_sql, "full_row_compare_sql": comparison_sql},
            }

    def _generate_migration_bundle(self, context: dict[str, Any], *, verify_only: bool) -> tuple[str, str, str, str]:
        from_table = self._source_table_prompt_value(context)
        to_table = self._qualify_to_table(str(context.get("to_table") or "").strip(), dict(context.get("db_config") or {}))
        ddl_info = self._ddl_info_block(context, from_table, to_table)
        mappings = self._mapping_info(context.get("mapping_details") or [])
        existing_migration_sql = str(context.get("saved_migration_sql") or context.get("current_migration_sql") or "")
        mode = "VERIFY_ONLY" if verify_only else "FULL_GENERATE"
        prompt = f"""You are an Oracle 19c migration and verification SQL generator.
Return exactly one valid JSON object, no markdown:
{{"migration_sql":"...","verification_sql":"...","full_row_compare_sql":"..."}}

Mode: {mode}
Source dataset/table: {from_table}
Target table: {to_table}
Source filter: {context.get('condition') or '(none)'}

[DDL]
{ddl_info}

[Mappings]
{mappings}

[Required migration SQL]
Use INSERT INTO target (target columns...) SELECT source expressions... .
When Mode is VERIFY_ONLY, return the existing migration_sql unchanged:
{existing_migration_sql}

[Required count verification SQL]
Return one Oracle SELECT with FROM (SELECT COUNT(*) TOT, COUNT(source non-LOB columns)... ) S,
(SELECT COUNT(*) TOT, COUNT(target non-LOB columns)... ) T.  Use the same source scope as migration.

[Required full-row verification SQL]
Return one executable Oracle WITH query. It must:
1. Include ASIS_ROWS and TOBE_ROWS CTEs.
2. Apply each MIG_SQL source expression to the matching target column by INSERT/SELECT position.
3. Serialize only target columns listed in the T-side COUNT(target_column) expressions; omit TOT and LOB/LONG columns.
4. Use schema-qualified source/target table names and aliases valid in their own CTE scope.
5. Produce exactly these final columns in this order:
   ROW_NO, COMPARE_RESULT, ASIS_CONCAT, TOBE_CONCAT.
6. Order both datasets by the complete ROW_CONCAT and pair them with ROW_NUMBER().
7. Set COMPARE_RESULT to MATCH when the concat values match, otherwise MISMATCH.
8. Do not execute or embed MIG_SQL as PL/SQL; only create the comparison SELECT.
"""
        raw, used_model = self._call_llm_json(
            system_anthropic="Return only the requested Oracle SQL JSON object.",
            system_openai="Return only the requested Oracle SQL JSON object.",
            prompt=prompt,
            config=dict(context.get("llm_config") or {}),
        )
        response = self._extract_json_object(raw)
        return (
            str(response.get("migration_sql") or ""),
            str(response.get("verification_sql") or ""),
            str(response.get("full_row_compare_sql") or ""),
            used_model,
        )

    def _generate_full_row_compare_only(self, context: dict[str, Any]) -> tuple[str, str]:
        migration_sql = str(context.get("saved_migration_sql") or context.get("current_migration_sql") or "")
        verification_sql = str(context.get("saved_verification_sql") or context.get("current_v_sql") or context.get("verification_sql") or "")
        prompt = f"""Return exactly one valid JSON object: {{"full_row_compare_sql":"..."}}.
Create an executable Oracle 19c WITH query for full-row comparison.
Use this existing MIG_SQL for target-column to source-expression mapping:
{migration_sql}

Use this existing Count Verify SQL to identify the T-side target COUNT(column) list and target scope:
{verification_sql}

The final SELECT columns must be ROW_NO, COMPARE_RESULT, ASIS_CONCAT, TOBE_CONCAT in that order.
Use ROW_NUMBER() over ORDER BY complete ROW_CONCAT, and do not include markdown."""
        raw, used_model = self._call_llm_json(
            system_anthropic="Return only the requested Oracle SQL JSON object.",
            system_openai="Return only the requested Oracle SQL JSON object.",
            prompt=prompt,
            config=dict(context.get("llm_config") or {}),
        )
        response = self._extract_json_object(raw)
        return str(response.get("full_row_compare_sql") or ""), used_model
