"""Experimental 10C executor: LLM creates MIG/count SQL; code builds PK-based Verify2 SQL."""

from __future__ import annotations

import json
import importlib.util
from pathlib import Path
from typing import Any


_executor2_path = Path(__file__).with_name("10C_migOneJobPocExecutor2.py")
_executor2_spec = importlib.util.spec_from_file_location("smartmigrate_executor2_base", _executor2_path)
if _executor2_spec is None or _executor2_spec.loader is None:
    raise ImportError(f"Could not load Executor2 base: {_executor2_path}")
_executor2_module = importlib.util.module_from_spec(_executor2_spec)
_executor2_spec.loader.exec_module(_executor2_module)

Executor2Base = _executor2_module.NewType10CMigOneJobPocExecutor2
FAIL_TEST2 = _executor2_module.FAIL_TEST2


class NewType10CMigOneJobPocExecutor3(Executor2Base):
    """PK-based verifier experiment, isolated from deterministic Executor2."""

    display_name = "10C MIG One Job Executor 3 (LLM Full-Row Verify)"
    description = "Generates migration/count SQL by LLM and deterministically builds primary-key comparison SQL."
    name = "NewType10CMigOneJobPocExecutor3"

    def _node_generate_sql(self, context: dict[str, Any]) -> dict[str, Any]:
        try:
            verify_only = context.get("failure_status") == "FAIL-TEST"
            migration_sql, verification_sql, used_model = self._generate_migration_bundle(context, verify_only=verify_only)
            if verify_only:
                migration_sql = str(
                    context.get("saved_migration_sql")
                    or context.get("current_migration_sql")
                    or context.get("migration_sql")
                    or ""
                ).strip()
            migration_sql = self._clean_sql_statement(migration_sql)
            verification_sql = self._clean_sql_statement(verification_sql)
            if not migration_sql:
                raise ValueError("LLM response did not include migration_sql")
            if not verification_sql:
                raise ValueError("LLM response did not include verification_sql")
            return {
                "stage": "GENERATE_SQL",
                "status": "PASS",
                "message": f"migration/count SQL generated by LLM model={used_model}",
                "outputs": {
                    "migration_sql": migration_sql,
                    "verification_sql": verification_sql,
                    "generated_sql_columns": ["VERIFY_SQL"] if verify_only else ["MIG_SQL", "VERIFY_SQL"],
                    "llm_model": used_model,
                    "generated_sql_saved": False,
                },
            }
        except Exception as exc:
            return {
                "stage": "GENERATE_SQL",
                "status": "FAIL-INSERT",
                "message": f"migration SQL bundle generation failed: {exc}",
                "outputs": {
                    "migration_sql": context.get("current_migration_sql") or context.get("migration_sql", ""),
                    "verification_sql": context.get("current_v_sql") or context.get("verification_sql", ""),
                },
            }

    def _node_verify_records(self, context: dict[str, Any]) -> dict[str, Any]:
        """Deterministically build and execute primary-key comparison SQL."""
        migration_sql = str(context.get("saved_migration_sql") or context.get("current_migration_sql") or context.get("migration_sql") or "")
        comparison_sql = ""
        try:
            comparison_sql, compare_columns, pk_columns = self._build_pk_compare_sql(
                migration_sql,
                str(context.get("current_v_sql") or context.get("verification_sql") or ""),
                context,
            )
            self._save_verify2_sql(dict(context.get("db_config") or {}), int(context["map_id"]), comparison_sql)
            result = self._execute_pk_comparison(
                dict(context.get("db_config") or {}),
                comparison_sql,
                pk_columns,
            )
            result["compared_columns"] = compare_columns
            result["pk_columns"] = pk_columns
            detail_json = json.dumps(result, ensure_ascii=False, default=str)
            return {
                "stage": "VERIFY_RECORDS",
                "status": "PASS" if result["ok"] else FAIL_TEST2,
                "message": result["summary"],
                "outputs": {
                    "record_projection_sql": comparison_sql,
                    "full_row_compare_sql": comparison_sql,
                    "saved_verification2_sql": comparison_sql,
                    "compared_columns": compare_columns,
                    "pk_columns": pk_columns,
                    "record_verify_result": result,
                    "record_verify_detail": detail_json,
                },
            }
        except Exception as exc:
            return {
                "stage": "VERIFY_RECORDS",
                "status": FAIL_TEST2,
                "message": f"PK verification failed: {exc}",
                "outputs": {"record_projection_sql": comparison_sql, "full_row_compare_sql": comparison_sql, "saved_verification2_sql": comparison_sql},
            }

    def _generate_migration_bundle(self, context: dict[str, Any], *, verify_only: bool) -> tuple[str, str, str]:
        from_table = self._source_table_prompt_value(context)
        to_table = self._qualify_to_table(str(context.get("to_table") or "").strip(), dict(context.get("db_config") or {}))
        ddl_info = self._ddl_info_block(context, from_table, to_table)
        mappings = self._mapping_info(context.get("mapping_details") or [])
        existing_migration_sql = str(context.get("saved_migration_sql") or context.get("current_migration_sql") or "")
        mode = "VERIFY_ONLY" if verify_only else "FULL_GENERATE"
        prompt = f"""You are an Oracle 19c migration and verification SQL generator.
Return exactly one valid JSON object, no markdown:
{{"migration_sql":"...","verification_sql":"..."}}

Mode: {mode}
Source dataset/table: {from_table}
Target table: {to_table}
Source filter: {context.get('condition') or '(none)'}

[DDL]
{ddl_info}

[Mappings]
{mappings}

[Required migration SQL]
Use INSERT INTO target (target columns...) SELECT source expressions... .
When Mode is VERIFY_ONLY, return the existing migration_sql unchanged:
{existing_migration_sql}

[Required count verification SQL]
Return one Oracle SELECT with FROM (SELECT COUNT(*) TOT, COUNT(source non-LOB columns)... ) S,
(SELECT COUNT(*) TOT, COUNT(target non-LOB columns)... ) T.
Apply the identical source filter to MIG_SQL and the S-side dataset. The T-side dataset must identify only this migration job's target rows.

"""
        raw, used_model = self._call_llm_json(
            system_anthropic="Return only the requested Oracle SQL JSON object.",
            system_openai="Return only the requested Oracle SQL JSON object.",
            prompt=prompt,
            config=dict(context.get("llm_config") or {}),
        )
        response = self._extract_json_object(raw)
        return (
            str(response.get("migration_sql") or ""),
            str(response.get("verification_sql") or ""),
            used_model,
        )

    def _build_pk_compare_sql(self, migration_sql: str, verification_sql: str, context: dict[str, Any]) -> tuple[str, list[str], list[str]]:
        """Build Verify2 from MIG/VERIFY parsing, matching rows only by target PK."""
        _, target_count_sql = self._extract_count_verify_datasets(verification_sql)
        compare_columns = self._count_verify_target_columns(target_count_sql)
        if not compare_columns:
            raise ValueError("PK_VERIFY could not find target COUNT(column) expressions in VERIFY_SQL")
        pk_columns = self._target_pk_columns_for_compare(context)
        migration_expressions = self._migration_target_expressions(migration_sql)
        required_columns = list(dict.fromkeys([*pk_columns, *compare_columns]))
        missing = [column for column in required_columns if column not in migration_expressions]
        if missing:
            raise ValueError(f"PK_VERIFY target columns are absent from MIG_SQL INSERT list: {missing}")

        target_from_clause = self._select_from_clause(target_count_sql)
        target_alias = self._target_from_alias(target_from_clause)
        source_from_clause = self._migration_source_from_clause(migration_sql)
        asis_projection = ",\n                       ".join(
            f"{migration_expressions[column]} AS {column}" for column in required_columns
        )
        tobe_projection = ",\n                       ".join(
            f"{target_alias + '.' if target_alias else ''}{column} AS {column}" for column in required_columns
        )
        pk_join = "\n   AND ".join(
            f"(A.{column} = T.{column} OR (A.{column} IS NULL AND T.{column} IS NULL))" for column in pk_columns
        )
        value_compare_columns = [column for column in compare_columns if column not in pk_columns]
        value_match = "\n           AND ".join(
            f"(A.{column} = T.{column} OR (A.{column} IS NULL AND T.{column} IS NULL))" for column in value_compare_columns
        ) or "1 = 1"
        pk_projection = ",\n       ".join(
            f"COALESCE(A.{column}, T.{column}) AS {column}" for column in pk_columns
        )
        presence_column = pk_columns[0]
        sql = f"""SELECT {pk_projection},
       CASE
           WHEN A.{presence_column} IS NULL OR T.{presence_column} IS NULL THEN 'MISMATCH'
           WHEN {value_match} THEN 'MATCH'
           ELSE 'MISMATCH'
       END AS COMPARE_RESULT
  FROM (
        SELECT {asis_projection}
        {source_from_clause}
       ) A
  FULL OUTER JOIN (
        SELECT {tobe_projection}
        {target_from_clause}
       ) T
    ON {pk_join}"""
        return sql, compare_columns, pk_columns

    def _target_pk_columns_for_compare(self, context: dict[str, Any]) -> list[str]:
        columns = [self._clean_identifier(str(column)) for column in context.get("target_pk_columns") or [] if str(column).strip()]
        if not columns:
            raise ValueError("PK_VERIFY requires target primary-key columns; target table has no usable PK")
        return columns

    def _execute_pk_comparison(self, db_config: dict[str, Any], comparison_sql: str, pk_columns: list[str]) -> dict[str, Any]:
        """Run PK-based comparison SQL returning PK columns and COMPARE_RESULT only."""
        mismatch_samples: list[dict[str, Any]] = []
        match_samples: list[dict[str, Any]] = []
        mismatch_count = 0
        compared_rows = 0
        with self._connect(db_config) as conn:
            cur = conn.cursor()
            cur.execute(comparison_sql)
            for db_row in cur:
                compared_rows += 1
                *pk_values, compare_result = db_row
                row = {
                    "pk_values": {
                        column: self._record_log_value(value)
                        for column, value in zip(pk_columns, pk_values, strict=True)
                    },
                    "compare_result": str(compare_result or ""),
                }
                if row["compare_result"] == "MISMATCH":
                    mismatch_count += 1
                    if len(mismatch_samples) < 5:
                        mismatch_samples.append(row)
                elif len(match_samples) < 5:
                    match_samples.append(row)
        samples = mismatch_samples if mismatch_samples else match_samples
        return {
            "ok": mismatch_count == 0,
            "comparison_sql": comparison_sql,
            "compared_rows": compared_rows,
            "mismatch_count": mismatch_count,
            "summary": f"PK verification compared={compared_rows}, mismatched={mismatch_count}",
            "rows": samples,
        }

    def _record_verify_log_body(self, state: dict[str, Any]) -> str:
        """Render the PK comparison SQL and up to five key-based results."""
        comparison_sql = str(state.get("record_projection_sql") or "").strip()
        result = dict(state.get("record_verify_result") or {})
        parts = [
            "[PK_COMPARE_SQL]",
            comparison_sql or "(comparison SQL unavailable)",
            "",
            "[PK_COMPARE_SUMMARY]",
            f"pk_columns={result.get('pk_columns') or []}",
            f"compared_columns={result.get('compared_columns') or []}",
            f"compared_rows={result.get('compared_rows') or 0}",
            f"mismatch_count={result.get('mismatch_count') or 0}",
            f"result={result.get('summary') or ''}",
        ]
        for index, row in enumerate(result.get("rows") or [], start=1):
            parts.extend(
                [
                    "",
                    f"[CASE {index}] PK={row.get('pk_values') or {}} RESULT={row.get('compare_result') or ''}",
                ]
            )
        if not result:
            detail = str(state.get("record_verify_detail") or "").strip()
            if detail:
                parts.extend(["", "[PK_VERIFY_ERROR_DETAIL]", detail])
        return "\n".join(parts)
