SET DEFINE OFF;

PROMPT === SmartMigrate table comments ===

COMMENT ON TABLE NEXT_MIG_INFO IS 'DB 이관 작업 마스터. 배치가 USE_YN, STATUS, PRIORITY 기준으로 실행 대상을 고른다.';
COMMENT ON COLUMN NEXT_MIG_INFO.MAP_ID IS '이관 작업 식별자. 상세 매핑과 로그가 이 값을 참조한다.';
COMMENT ON COLUMN NEXT_MIG_INFO.MAP_TYPE IS '매핑 유형. TABLE은 테이블 기준, COMPLEX는 가상 SQL 기준으로 생성한다.';
COMMENT ON COLUMN NEXT_MIG_INFO.FR_TABLE IS '원천 테이블 또는 원천 조회 SQL. MIG_SQL 생성 시 FROM 기준이다.';
COMMENT ON COLUMN NEXT_MIG_INFO.TO_TABLE IS '대상 테이블. INSERT 대상이며 같은 대상 안에서는 PRIORITY 순서로 실행한다.';
COMMENT ON COLUMN NEXT_MIG_INFO.USE_YN IS 'Y인 경우 배치 작업 대상, N인 경우 이관 대상에서 제외한다.';
COMMENT ON COLUMN NEXT_MIG_INFO.TRUNC_YN IS 'Y인 경우 이관 전 대상 초기화가 필요함을 표시한다.';
COMMENT ON COLUMN NEXT_MIG_INFO.PRIORITY IS '낮을수록 먼저 실행한다. 같은 대상 테이블의 선행 순서 판단에 사용한다.';
COMMENT ON COLUMN NEXT_MIG_INFO.STATUS IS 'NULL인 경우 배치 작업 대상. PASS는 완료, FAIL 계열은 실패 상태다.';
COMMENT ON COLUMN NEXT_MIG_INFO.USER_EDITED IS 'Y인 경우 사용자가 저장한 MIG_SQL 또는 VERIFY_SQL을 우선 사용한다.';
COMMENT ON COLUMN NEXT_MIG_INFO.PRIOR_MAP_ID IS '선행 MAP_ID. 선행 작업이 PASS가 아니면 현재 작업은 대기한다.';
COMMENT ON COLUMN NEXT_MIG_INFO.CONDITION IS '원천 필터 조건. MIG_SQL과 VERIFY_SQL 생성 시 WHERE 조건으로 반영한다.';
COMMENT ON COLUMN NEXT_MIG_INFO.MIG_SQL IS '최종 실행한 이관 INSERT SQL. 재시도 중간 SQL은 저장하지 않는다.';
COMMENT ON COLUMN NEXT_MIG_INFO.VERIFY_SQL IS '최종 검증 SQL. 검증 통과 여부 판단에 사용한 SQL을 저장한다.';
COMMENT ON COLUMN NEXT_MIG_INFO.BATCH_CNT IS '이관 배치 실행 횟수. 재실행 판단과 모니터링에 사용한다.';
COMMENT ON COLUMN NEXT_MIG_INFO.ELAPSED_SECONDS IS '최근 이관 실행 소요 시간. 대시보드 성능 지표로 사용한다.';
COMMENT ON COLUMN NEXT_MIG_INFO.RETRY_COUNT IS '최근 이관 재시도 횟수. 실패 분석과 재처리 판단에 사용한다.';
COMMENT ON COLUMN NEXT_MIG_INFO.CREATED_AT IS '작업 생성 시각. 최초 등록 시점을 기록한다.';
COMMENT ON COLUMN NEXT_MIG_INFO.UPD_TS IS '최근 수정 시각. 상태나 SQL 변경 시 갱신한다.';

COMMENT ON TABLE NEXT_MIG_INFO_DTL IS 'DB 이관 컬럼 매핑 상세. MAP_ID별 원천 컬럼과 대상 컬럼을 정의한다.';
COMMENT ON COLUMN NEXT_MIG_INFO_DTL.MAP_DTL IS '컬럼 매핑 식별자. 상세 row 정렬과 구분에 사용한다.';
COMMENT ON COLUMN NEXT_MIG_INFO_DTL.MAP_ID IS '이관 작업 식별자. NEXT_MIG_INFO의 MAP_ID와 연결한다.';
COMMENT ON COLUMN NEXT_MIG_INFO_DTL.FR_COL IS '원천 컬럼 또는 표현식. MIG_SQL SELECT 절 생성 기준이다.';
COMMENT ON COLUMN NEXT_MIG_INFO_DTL.TO_COL IS '대상 컬럼. 빈 값이면 INSERT 대상 컬럼에서 제외한다.';

COMMENT ON TABLE NEXT_MIG_LOG IS 'DB 이관 실행 로그. 생성, 실행, 검증, 실패 원인을 단계별로 남긴다.';
COMMENT ON COLUMN NEXT_MIG_LOG.LOG_ID IS '로그 식별자. MIGRATION_LOG_SEQ로 증가시키며 최신 로그 정렬에 사용한다.';
COMMENT ON COLUMN NEXT_MIG_LOG.MAP_ID IS '관련 이관 작업 식별자. MAP_ID별 실행 이력을 조회한다.';
COMMENT ON COLUMN NEXT_MIG_LOG.MIG_KIND IS '이관 구분. 기본값 DB_MIG로 DB 이관 로그를 구분한다.';
COMMENT ON COLUMN NEXT_MIG_LOG.LOG_TYPE IS '로그 유형. GENERATE_SQL, ROW_ERROR, JOB_FAIL 등 원인 분류에 사용한다.';
COMMENT ON COLUMN NEXT_MIG_LOG.LOG_LEVEL IS '로그 등급. INFO, WARN, ERROR 기준으로 장애 분석에 사용한다.';
COMMENT ON COLUMN NEXT_MIG_LOG.STEP_NAME IS '실행 단계명. SQL 생성, 이관 실행, 검증 단계 구분에 사용한다.';
COMMENT ON COLUMN NEXT_MIG_LOG.STATUS IS '단계 처리 상태. PASS, FAIL, WAITING 등 단계 결과를 기록한다.';
COMMENT ON COLUMN NEXT_MIG_LOG.MESSAGE IS '로그 메시지. 실패 요약과 사용자 안내 문구로 사용한다.';
COMMENT ON COLUMN NEXT_MIG_LOG.RETRY_COUNT IS '로그 발생 시점의 재시도 번호. 반복 실패 흐름을 추적한다.';
COMMENT ON COLUMN NEXT_MIG_LOG.GENERATE_SQL IS '해당 단계에서 생성 또는 실행한 SQL. 실패 재현과 분석에 사용한다.';
COMMENT ON COLUMN NEXT_MIG_LOG.CREATED_AT IS '로그 생성 시각. 실행 이력 시간순 조회에 사용한다.';
COMMENT ON COLUMN NEXT_MIG_LOG.UPD_TS IS '로그 수정 시각. 보정 또는 후처리 시 갱신한다.';

COMMENT ON TABLE NEXT_SQL_INFO IS 'SQL 변환 작업 마스터. 변환, 튜닝, 바인드, 검증, 포맷팅 결과를 저장한다.';
COMMENT ON COLUMN NEXT_SQL_INFO.TAG_KIND IS 'Mapper 태그 유형. SELECT가 아니면 변환 후 튜닝 없이 완료 처리할 수 있다.';
COMMENT ON COLUMN NEXT_SQL_INFO.SPACE_NM IS 'Mapper namespace. SQL_ID와 함께 SQL 작업의 유일 키로 사용한다.';
COMMENT ON COLUMN NEXT_SQL_INFO.SQL_ID IS 'Mapper SQL 식별자. SPACE_NM과 함께 작업을 조회하고 갱신한다.';
COMMENT ON COLUMN NEXT_SQL_INFO.FR_SQL IS '원천 SQL. EDIT_FR_SQL이 없을 때 변환 입력으로 사용한다.';
COMMENT ON COLUMN NEXT_SQL_INFO.EDIT_FR_SQL IS '사용자 수정 원천 SQL. 값이 있으면 FR_SQL보다 우선 사용한다.';
COMMENT ON COLUMN NEXT_SQL_INFO.TARGET_TABLE IS '원천 테이블 후보 목록. 매핑 룰과 RAG 룰 검색 조건으로 사용한다.';
COMMENT ON COLUMN NEXT_SQL_INFO.TO_SQL IS '변환된 대상 SQL. 변환 성공 시 저장하고 튜닝 입력으로 사용한다.';
COMMENT ON COLUMN NEXT_SQL_INFO.TUNED_TO_SQL IS '튜닝된 대상 SQL. 튜닝 성공 시 저장하고 포맷팅 입력으로 사용한다.';
COMMENT ON COLUMN NEXT_SQL_INFO.TUNED_RESULT IS '튜닝 분석 결과. 튜닝 근거와 검증 결과를 저장한다.';
COMMENT ON COLUMN NEXT_SQL_INFO.STATUS_TUNING IS '튜닝 상태. READY 또는 FAIL 계열이면 튜닝 배치 대상이다.';
COMMENT ON COLUMN NEXT_SQL_INFO.TUNED_FR_SQL IS '바인드 적용 원천 SQL. 바인드 전처리 결과를 저장한다.';
COMMENT ON COLUMN NEXT_SQL_INFO.BIND_SQL IS '바인드 SQL. 테스트 SQL 생성과 검증 실행에 사용한다.';
COMMENT ON COLUMN NEXT_SQL_INFO.BIND_SET IS '바인드 변수 정보. 테스트 실행에 필요한 값 묶음을 저장한다.';
COMMENT ON COLUMN NEXT_SQL_INFO.TEST_SQL IS '검증 SQL. FROM_COUNT와 TO_COUNT 비교 결과로 PASS 여부를 판단한다.';
COMMENT ON COLUMN NEXT_SQL_INFO.STATUS_CONVERSION IS '변환 상태. NULL이면 변환 배치 대상, PASS 계열이면 튜닝 후보가 된다.';
COMMENT ON COLUMN NEXT_SQL_INFO.LOG IS '최근 처리 로그. UI와 장애 분석에서 최신 실패 요약으로 사용한다.';
COMMENT ON COLUMN NEXT_SQL_INFO.USER_EDITED IS 'Y인 경우 사용자가 보정한 SQL을 우선 보존한다.';
COMMENT ON COLUMN NEXT_SQL_INFO.SQL_LENGTH IS 'SQL 길이 분류. SHORT 또는 LONG 기준으로 실패 분석에 사용한다.';
COMMENT ON COLUMN NEXT_SQL_INFO.MAP_TYPE IS '매핑 유형. SQL 변환 난이도와 처리 분기 분석에 사용한다.';
COMMENT ON COLUMN NEXT_SQL_INFO.PRIORITY IS '낮을수록 먼저 실행한다. URGENT 재처리 시 더 낮은 값으로 조정한다.';
COMMENT ON COLUMN NEXT_SQL_INFO.BATCH_CNT IS 'SQL 파이프라인 실행 횟수. 최대 배치 횟수 제한에 사용한다.';
COMMENT ON COLUMN NEXT_SQL_INFO.RETRY_COUNT IS '최근 SQL 처리 재시도 횟수. 실패 재처리 판단에 사용한다.';
COMMENT ON COLUMN NEXT_SQL_INFO.FORMATTED_SQL IS '최종 정리 SQL. 값이 비어 있고 튜닝 PASS이면 포맷팅 대상이다.';
COMMENT ON COLUMN NEXT_SQL_INFO.BLOCK_RAG_CONTENT IS '적용 후보 RAG 내용. 튜닝 근거와 프롬프트 컨텍스트로 사용한다.';
COMMENT ON COLUMN NEXT_SQL_INFO.UPD_TS IS '최근 수정 시각. 배치 정렬과 최신 상태 표시 기준이다.';

COMMENT ON TABLE NEXT_SQL_LOG IS 'SQL 파이프라인 단계 로그. 변환, 튜닝, 바인드, 테스트, 포맷팅 이력을 남긴다.';
COMMENT ON COLUMN NEXT_SQL_LOG.LOG_ID IS 'SQL 로그 식별자. 자동 증가하며 최신 로그 정렬에 사용한다.';
COMMENT ON COLUMN NEXT_SQL_LOG.CREATED_AT IS '로그 생성 시각. 단계별 처리 시간 추적 기준이다.';
COMMENT ON COLUMN NEXT_SQL_LOG.SPACE_NM IS 'Mapper namespace. SQL 작업과 로그를 연결한다.';
COMMENT ON COLUMN NEXT_SQL_LOG.SQL_ID IS 'Mapper SQL 식별자. SQL 작업과 로그를 연결한다.';
COMMENT ON COLUMN NEXT_SQL_LOG.SQL_INFO_ROWID IS 'NEXT_SQL_INFO ROWID. 같은 SQL_ID 중 특정 row 추적에 사용한다.';
COMMENT ON COLUMN NEXT_SQL_LOG.SQL_KIND IS 'SQL 산출물 유형. TOBE_SQL, BIND_SQL, TEST_SQL 등으로 구분한다.';
COMMENT ON COLUMN NEXT_SQL_LOG.SQL_CONTENT IS '생성 SQL 내용. 단계별 산출물과 실패 재현에 사용한다.';
COMMENT ON COLUMN NEXT_SQL_LOG.STATUS IS '단계 상태. PASS, FAIL, NA 등 단계 결과를 기록한다.';
COMMENT ON COLUMN NEXT_SQL_LOG.PROMPT_NAME IS '사용한 프롬프트명. 프롬프트별 품질 분석에 사용한다.';
COMMENT ON COLUMN NEXT_SQL_LOG.MODEL_NAME IS '사용한 모델명. 모델별 처리 결과 비교에 사용한다.';
COMMENT ON COLUMN NEXT_SQL_LOG.BATCH_NO IS '배치 실행 번호. 한 번의 배치 묶음을 구분한다.';
COMMENT ON COLUMN NEXT_SQL_LOG.CYCLE_NO IS '파이프라인 순환 번호. 반복 처리 흐름을 구분한다.';
COMMENT ON COLUMN NEXT_SQL_LOG.ELAPSED_SECONDS IS '단계 소요 시간. 느린 단계 분석에 사용한다.';
COMMENT ON COLUMN NEXT_SQL_LOG.ATTEMPT_NO IS '시도 번호. 재시도별 결과 차이를 추적한다.';
COMMENT ON COLUMN NEXT_SQL_LOG.STAGE_NAME IS '단계명. GENERATE, VALIDATE 등 처리 위치를 표시한다.';
COMMENT ON COLUMN NEXT_SQL_LOG.ERROR_MESSAGE IS '오류 상세. 실패 원인 분석과 재처리 안내에 사용한다.';

COMMENT ON TABLE NEXT_MIG_RAG_INFO IS 'SQL 변환과 튜닝 RAG 규칙. CATEGORY, RULE_TYPE, SOURCE_TABLES로 검색한다.';
COMMENT ON COLUMN NEXT_MIG_RAG_INFO.RAG_ID IS 'RAG 규칙 식별자. 규칙 관리와 사용 횟수 갱신에 사용한다.';
COMMENT ON COLUMN NEXT_MIG_RAG_INFO.CATEGORY IS '규칙 분류. SQL_CONVERSION 또는 SQL_TUNING 흐름에서 선택한다.';
COMMENT ON COLUMN NEXT_MIG_RAG_INFO.RULE_TYPE IS '규칙 유형. SEARCH, PATTERN, GUIDE 등 적용 방식을 구분한다.';
COMMENT ON COLUMN NEXT_MIG_RAG_INFO.SOURCE_TABLES IS '원천 테이블 목록. SQL의 TARGET_TABLE과 매칭해 후보 규칙을 찾는다.';
COMMENT ON COLUMN NEXT_MIG_RAG_INFO.USE_YN IS 'Y인 경우 RAG 검색 대상, N인 경우 프롬프트 후보에서 제외한다.';
COMMENT ON COLUMN NEXT_MIG_RAG_INFO.GUIDANCE_TEXT IS 'LLM 지침 문구. 변환 또는 튜닝 프롬프트에 포함한다.';
COMMENT ON COLUMN NEXT_MIG_RAG_INFO.SOURCE_SQL IS '예시 원천 SQL. 유사 패턴 설명과 Few-shot 예시에 사용한다.';
COMMENT ON COLUMN NEXT_MIG_RAG_INFO.TARGET_SQL IS '예시 대상 SQL. 변환 또는 튜닝 결과 예시로 사용한다.';
COMMENT ON COLUMN NEXT_MIG_RAG_INFO.HIT_CNT IS '규칙 사용 횟수. 선택된 규칙의 활용도를 누적한다.';
COMMENT ON COLUMN NEXT_MIG_RAG_INFO.CREATED_AT IS '규칙 생성 시각. 등록 이력 확인에 사용한다.';
COMMENT ON COLUMN NEXT_MIG_RAG_INFO.UPDATED_AT IS '규칙 수정 시각. 최신 지침 여부 확인에 사용한다.';

COMMENT ON TABLE NEXT_BATCH_CONTROL IS '배치 실행 제어 테이블. 중복 실행 방지와 중지 요청 상태를 저장한다.';
COMMENT ON COLUMN NEXT_BATCH_CONTROL.CONTROL_NAME IS '제어 row 이름. BATCH_AGENT row 하나를 기준으로 사용한다.';
COMMENT ON COLUMN NEXT_BATCH_CONTROL.STATUS IS '배치 상태. RUNNING이면 실행 중, STOPPED이면 시작 가능 상태다.';
COMMENT ON COLUMN NEXT_BATCH_CONTROL.RUN_ID IS '실행 식별자. 배치 로그와 현재 실행 회차를 연결한다.';
COMMENT ON COLUMN NEXT_BATCH_CONTROL.STOP_REQUESTED_YN IS 'Y인 경우 배치 worker가 다음 체크 시 중지 흐름으로 전환한다.';
COMMENT ON COLUMN NEXT_BATCH_CONTROL.LOOP_NO IS '현재 루프 번호. 배치 heartbeat와 로그 순서 확인에 사용한다.';
COMMENT ON COLUMN NEXT_BATCH_CONTROL.STARTED_AT IS '배치 시작 시각. 실행 시간 계산 기준이다.';
COMMENT ON COLUMN NEXT_BATCH_CONTROL.HEARTBEAT_AT IS '최근 생존 시각. 오래되면 비정상 종료 가능성으로 판단한다.';
COMMENT ON COLUMN NEXT_BATCH_CONTROL.STOP_REQUESTED_AT IS '중지 요청 시각. 사용자가 stop을 요청한 시간을 기록한다.';
COMMENT ON COLUMN NEXT_BATCH_CONTROL.STOPPED_AT IS '배치 중지 시각. 정상 종료 확인에 사용한다.';
COMMENT ON COLUMN NEXT_BATCH_CONTROL.UPDATED_AT IS '제어 row 수정 시각. 상태 변경과 heartbeat 갱신 기준이다.';
COMMENT ON COLUMN NEXT_BATCH_CONTROL.LAST_EVENT IS '최근 이벤트. 마지막 배치 동작 요약으로 표시한다.';
COMMENT ON COLUMN NEXT_BATCH_CONTROL.LAST_AGENT IS '최근 실행 agent. DB, SQL 변환, 튜닝, 포맷팅 중 하나를 기록한다.';
COMMENT ON COLUMN NEXT_BATCH_CONTROL.LAST_JOB_ID IS '최근 작업 식별자. 마지막 처리 job을 추적한다.';
COMMENT ON COLUMN NEXT_BATCH_CONTROL.LAST_JOB_STATUS IS '최근 작업 상태. 마지막 처리 결과를 대시보드에 표시한다.';
COMMENT ON COLUMN NEXT_BATCH_CONTROL.LAST_ERROR IS '최근 오류 상세. 배치 중단 또는 실패 원인을 저장한다.';
COMMENT ON COLUMN NEXT_BATCH_CONTROL.MESSAGE IS '제어 메시지. 현재 배치 상태 설명에 사용한다.';

COMMENT ON TABLE NEXT_BATCH_LOG IS '배치 루프 이력. start, stop, no job, error, job result를 기록한다.';
COMMENT ON COLUMN NEXT_BATCH_LOG.LOG_ID IS '배치 로그 식별자. 자동 증가하며 최신 이벤트 정렬에 사용한다.';
COMMENT ON COLUMN NEXT_BATCH_LOG.RUN_ID IS '실행 식별자. 하나의 batch run에 속한 로그를 묶는다.';
COMMENT ON COLUMN NEXT_BATCH_LOG.LOOP_NO IS '루프 번호. 배치가 몇 번째 순환에서 기록했는지 표시한다.';
COMMENT ON COLUMN NEXT_BATCH_LOG.EVENT_TYPE IS '이벤트 유형. START, NO_JOB, LOOP_ERROR, STOPPED 등으로 구분한다.';
COMMENT ON COLUMN NEXT_BATCH_LOG.AGENT_NAME IS '실행 agent 이름. 어떤 agent가 작업했는지 기록한다.';
COMMENT ON COLUMN NEXT_BATCH_LOG.JOB_ID IS '처리 작업 식별자. MAP_ID 또는 SQL 작업 키를 저장한다.';
COMMENT ON COLUMN NEXT_BATCH_LOG.JOB_STATUS IS '작업 결과 상태. PASS, FAIL, NO_JOB 등 배치 판단 결과를 저장한다.';
COMMENT ON COLUMN NEXT_BATCH_LOG.MESSAGE IS '이벤트 메시지. 배치 진행 상황 요약에 사용한다.';
COMMENT ON COLUMN NEXT_BATCH_LOG.ERROR_MESSAGE IS '오류 상세. LOOP_ERROR 또는 FATAL_ERROR 분석에 사용한다.';
COMMENT ON COLUMN NEXT_BATCH_LOG.SLEEP_SECONDS IS '대기 시간. 다음 루프 전 sleep 시간을 기록한다.';
COMMENT ON COLUMN NEXT_BATCH_LOG.STARTED_AT IS '이벤트 시작 시각. 루프별 처리 시간 계산 기준이다.';
COMMENT ON COLUMN NEXT_BATCH_LOG.FINISHED_AT IS '이벤트 종료 시각. 처리 완료 시각과 소요 시간 계산에 사용한다.';
COMMENT ON COLUMN NEXT_BATCH_LOG.ELAPSED_SECONDS IS '이벤트 소요 시간. 느린 작업과 장애 구간 분석에 사용한다.';

COMMENT ON TABLE NEXT_BATCH_COMMAND IS 'Supervisor worker가 DB에서 읽는 배치 명령 큐. 외부 UI나 운영 도구는 PENDING row로 명령을 전달한다.';
COMMENT ON COLUMN NEXT_BATCH_COMMAND.COMMAND_ID IS '배치 명령 식별자. 요청 순서와 처리 이력을 추적한다.';
COMMENT ON COLUMN NEXT_BATCH_COMMAND.CONTROL_NAME IS '명령 대상 제어 row 이름. 기본값은 BATCH_AGENT다.';
COMMENT ON COLUMN NEXT_BATCH_COMMAND.COMMAND_STATUS IS '명령 처리 상태. PENDING, CLAIMED, DONE, FAILED, CANCELLED 중 하나다.';
COMMENT ON COLUMN NEXT_BATCH_COMMAND.COMMAND_TYPE IS '명령 유형. USER_COMMAND, START, STOP 등 호출 출처나 목적을 구분한다.';
COMMENT ON COLUMN NEXT_BATCH_COMMAND.COMMAND_TEXT IS 'Supervisor가 이번 cycle에 반영할 명령 문자열.';
COMMENT ON COLUMN NEXT_BATCH_COMMAND.COMMAND_JSON IS '구조화된 명령 payload. action, map_id, sql_id, space_nm 등을 JSON으로 저장할 수 있다.';
COMMENT ON COLUMN NEXT_BATCH_COMMAND.REQUESTED_BY IS '명령 요청자 또는 호출 컴포넌트 이름.';
COMMENT ON COLUMN NEXT_BATCH_COMMAND.REQUESTED_AT IS '명령 요청 시각.';
COMMENT ON COLUMN NEXT_BATCH_COMMAND.CLAIMED_AT IS 'Supervisor worker가 명령을 가져간 시각.';
COMMENT ON COLUMN NEXT_BATCH_COMMAND.COMPLETED_AT IS 'Supervisor worker가 명령 처리를 완료한 시각.';
COMMENT ON COLUMN NEXT_BATCH_COMMAND.ERROR_MESSAGE IS '명령 처리 실패 시 오류 상세.';

COMMIT;
