"""Create NEXT_MIG_RAG_INFO for unified SQL conversion/tuning RAG rules.

Run:
  python scripts/create_mig_rag_info_table.py
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from scripts._bootstrap import ROOT_DIR
from dotenv import load_dotenv

load_dotenv(ROOT_DIR / ".env")

from smart_migrate.integrations.oracle.OracleConnection import get_connection, qualify_table_name


TABLE_NAME = qualify_table_name("NEXT_MIG_RAG_INFO")

DDL = f"""
CREATE TABLE {TABLE_NAME}
(
    RAG_ID        NUMBER GENERATED BY DEFAULT AS IDENTITY,
    CATEGORY      VARCHAR2(100) DEFAULT 'SQL_TUNING' NOT NULL,
    RULE_TYPE     VARCHAR2(30)  DEFAULT 'SEARCH' NOT NULL,
    SOURCE_TABLES VARCHAR2(1000),
    USE_YN        CHAR(1)       DEFAULT 'Y' NOT NULL,
    GUIDANCE_TEXT CLOB,
    SOURCE_SQL    CLOB,
    TARGET_SQL    CLOB,
    HIT_CNT       NUMBER        DEFAULT 0 NOT NULL,
    CREATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_NEXT_MIG_RAG_INFO PRIMARY KEY (RAG_ID),
    CONSTRAINT CK_NEXT_MIG_RAG_CATEGORY CHECK (CATEGORY IN ('SQL_CONVERSION', 'SQL_TUNING')),
    CONSTRAINT CK_NEXT_MIG_RAG_RULE_TYPE CHECK (RULE_TYPE IN ('GENERAL', 'SEARCH')),
    CONSTRAINT CK_NEXT_MIG_RAG_USE_YN CHECK (USE_YN IN ('Y', 'N'))
)
"""


def _split_table_owner_and_name(table: str) -> tuple[str | None, str]:
    value = (table or "").strip().upper()
    if "." in value:
        owner, name = value.split(".", 1)
        return owner.strip('"'), name.strip('"')
    return None, value.strip('"')


def table_exists(cur, table_name: str) -> bool:
    owner, name = _split_table_owner_and_name(table_name)
    if owner:
        cur.execute(
            "SELECT COUNT(*) FROM ALL_TABLES WHERE OWNER = :1 AND TABLE_NAME = :2",
            (owner, name),
        )
    else:
        cur.execute(
            "SELECT COUNT(*) FROM USER_TABLES WHERE TABLE_NAME = :1",
            (name,),
        )
    return int(cur.fetchone()[0] or 0) > 0


def main() -> None:
    with get_connection() as conn:
        cur = conn.cursor()
        if table_exists(cur, TABLE_NAME):
            print(f"{TABLE_NAME} already exists.")
            return
        cur.execute(DDL)
        conn.commit()
        print(f"{TABLE_NAME} created.")


if __name__ == "__main__":
    main()
